// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe            = require("reason-react/src/ReactDOMRe.js");
var ReasonReact           = require("reason-react/src/ReasonReact.js");
var TodoApp$ReactTemplate = require("./TodoApp.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, TodoApp$ReactTemplate.make(/* array */[])), "root");

/*  Not a pure module */
